# Generated by Django 5.0.6 on 2026-05-25 18:08

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Tenant',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255, unique=True)),
                ('slug', models.SlugField(max_length=100, unique=True)),
                ('fiscal_year_start_month', models.PositiveSmallIntegerField(default=1, help_text='1=January')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='EmissionRecord',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('source_type', models.CharField(choices=[('SAP_FUEL', 'SAP — Fuel Combustion'), ('SAP_PROCUREMENT', 'SAP — Procurement'), ('UTILITY_ELEC', 'Utility — Electricity'), ('TRAVEL_FLIGHT', 'Travel — Flight'), ('TRAVEL_HOTEL', 'Travel — Hotel'), ('TRAVEL_GROUND', 'Travel — Ground Transport')], max_length=20)),
                ('source_id', models.CharField(blank=True, help_text='Source-system identifier: SAP doc number, utility meter ID, Concur trip ID', max_length=255)),
                ('source_period_start', models.DateField(blank=True, help_text='Start of the reporting period this record covers', null=True)),
                ('source_period_end', models.DateField(blank=True, help_text='End of the reporting period this record covers', null=True)),
                ('activity_description', models.TextField(blank=True)),
                ('scope', models.CharField(choices=[('SCOPE_1', 'Scope 1 — Direct'), ('SCOPE_2', 'Scope 2 — Indirect (Energy)'), ('SCOPE_3', 'Scope 3 — Value Chain')], max_length=10)),
                ('ghg_category', models.CharField(blank=True, max_length=100)),
                ('ghg_category_code', models.CharField(blank=True, max_length=20)),
                ('activity_value', models.DecimalField(decimal_places=6, help_text='Normalized activity quantity in canonical unit', max_digits=18)),
                ('activity_unit', models.CharField(help_text='Canonical unit: L, kWh, km, nights', max_length=20)),
                ('original_value', models.DecimalField(blank=True, decimal_places=6, max_digits=18, null=True)),
                ('original_unit', models.CharField(blank=True, max_length=30)),
                ('emission_factor', models.DecimalField(decimal_places=8, help_text='kg CO2e per activity_unit', max_digits=18)),
                ('emission_factor_source', models.CharField(help_text="e.g. 'DEFRA 2023', 'EPA eGRID2022 RFCW', 'IPCC AR5'", max_length=255)),
                ('emission_factor_year', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('co2e_kg', models.DecimalField(decimal_places=4, help_text='activity_value × emission_factor, in kg CO2e', max_digits=18)),
                ('country_code', models.CharField(blank=True, max_length=3)),
                ('region', models.CharField(blank=True, help_text='State, eGRID subregion, SAP plant description, etc.', max_length=100)),
                ('facility_id', models.CharField(blank=True, help_text='SAP plant code, utility meter ID, Concur cost center', max_length=100)),
                ('facility_name', models.CharField(blank=True, max_length=255)),
                ('review_status', models.CharField(choices=[('PENDING', 'Pending Review'), ('FLAGGED', 'Flagged — Needs Attention'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected')], default='PENDING', max_length=10)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('review_notes', models.TextField(blank=True)),
                ('is_locked', models.BooleanField(default=False, help_text='True after analyst approval + lock-for-audit. Immutable thereafter.')),
                ('flag_reasons', models.JSONField(blank=True, default=list, help_text='List of auto-detected issues: zero value, outlier, future date, etc.')),
                ('is_edited', models.BooleanField(default=False)),
                ('original_activity_value', models.DecimalField(blank=True, decimal_places=6, help_text='Pre-edit value, set when analyst corrects activity_value', max_digits=18, null=True)),
                ('edited_at', models.DateTimeField(blank=True, null=True)),
                ('edit_reason', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('edited_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='edited_records', to=settings.AUTH_USER_MODEL)),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_records', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-source_period_end', 'source_type'],
            },
        ),
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('action', models.CharField(help_text='e.g. CREATED, APPROVED, REJECTED, FLAGGED, EDITED, LOCKED', max_length=50)),
                ('before_state', models.JSONField(blank=True, null=True)),
                ('after_state', models.JSONField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('actor', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_actions', to=settings.AUTH_USER_MODEL)),
                ('emission_record', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='audit_logs', to='core.emissionrecord')),
            ],
            options={
                'ordering': ['timestamp'],
            },
        ),
        migrations.CreateModel(
            name='IngestionBatch',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('source_type', models.CharField(choices=[('SAP', 'SAP Export (Fuel / Procurement)'), ('UTILITY', 'Utility Portal CSV (Electricity)'), ('TRAVEL', 'Corporate Travel Export (Concur-style)')], max_length=20)),
                ('filename', models.CharField(max_length=500)),
                ('raw_file', models.FileField(blank=True, null=True, upload_to='raw_uploads/%Y/%m/')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('PROCESSING', 'Processing'), ('DONE', 'Done'), ('FAILED', 'Failed')], default='PENDING', max_length=20)),
                ('row_count', models.IntegerField(default=0)),
                ('error_count', models.IntegerField(default=0)),
                ('warning_count', models.IntegerField(default=0)),
                ('parse_log', models.JSONField(blank=True, default=list)),
                ('notes', models.TextField(blank=True)),
                ('uploaded_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='uploaded_batches', to=settings.AUTH_USER_MODEL)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='batches', to='core.tenant')),
            ],
            options={
                'ordering': ['-uploaded_at'],
            },
        ),
        migrations.AddField(
            model_name='emissionrecord',
            name='batch',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='emission_records', to='core.ingestionbatch'),
        ),
        migrations.CreateModel(
            name='RawRecord',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('row_index', models.IntegerField(help_text='0-based row index in the source file')),
                ('raw_data', models.JSONField(help_text='Original parsed row as key-value dict')),
                ('parse_status', models.CharField(choices=[('OK', 'OK'), ('WARN', 'Warning'), ('ERROR', 'Error')], default='OK', max_length=10)),
                ('parse_errors', models.JSONField(blank=True, default=list)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('batch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='raw_records', to='core.ingestionbatch')),
            ],
            options={
                'ordering': ['batch', 'row_index'],
            },
        ),
        migrations.AddField(
            model_name='emissionrecord',
            name='raw_record',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='emission_record', to='core.rawrecord'),
        ),
        migrations.AddField(
            model_name='emissionrecord',
            name='tenant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='emission_records', to='core.tenant'),
        ),
        migrations.AddIndex(
            model_name='emissionrecord',
            index=models.Index(fields=['tenant', 'review_status'], name='core_emissi_tenant__af7a87_idx'),
        ),
        migrations.AddIndex(
            model_name='emissionrecord',
            index=models.Index(fields=['tenant', 'scope'], name='core_emissi_tenant__fc19e0_idx'),
        ),
        migrations.AddIndex(
            model_name='emissionrecord',
            index=models.Index(fields=['tenant', 'source_type'], name='core_emissi_tenant__44e112_idx'),
        ),
        migrations.AddIndex(
            model_name='emissionrecord',
            index=models.Index(fields=['tenant', 'source_period_start', 'source_period_end'], name='core_emissi_tenant__d643a5_idx'),
        ),
        migrations.AddIndex(
            model_name='emissionrecord',
            index=models.Index(fields=['batch'], name='core_emissi_batch_i_0918bd_idx'),
        ),
    ]
